// Generated by CoffeeScript 1.4.0
(function() {
  var TestClass;

  TestClass = (function() {

    function TestClass() {}

    TestClass.prototype.hello = function() {
      return console.log("hello world");
    };

    return TestClass;

  })();

}).call(this);
